name: FTP Deploy to cPanel

on:
  push:
    branches:
      - dev

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node (required by some ftp actions)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.zhndev.site
          username: zhndev@test.zhndev.site
          password: m*07x;t4OpU7Nbo#
          local-dir: ./
          server-dir: /home/zhndev/test.zhndev.site/
          # server: ${{ secrets.FTP_HOST }}
          # username: ${{ secrets.FTP_USERNAME }}
          # password: ${{ secrets.FTP_PASSWORD }}
          # local-dir: ./
          # server-dir: ${{ secrets.FTP_TARGET }}
          # optional: exclude GitHub workflow files from upload
          exclude: ".git/**,.github/**,.gitignore"
